d = [
  "wYtcP2me",
  "cdvofSosWRTRWOP2CLumW4RdJ8kW",
  "sxxcQMFcNq==",
  "WPJcUCoqwuO=",
  "WR82WP4=",
  "WRvNfCoxhSo0WRtcRCoJAwaKWRtcLmoXW77cVCo8dHCHWOy=",
  "vmkbWRpcHsZcR8oBW7uCWPxdGmk6WRqu",
  "emoxWRpdIZS=",
  "WOepaCooBW==",
  "WPKDcCogFW==",
  "FmkpW6JdMCof",
  "oSoCW57cM1q=",
  "aCkTWQ0Gy0mAsx3dHaxdQdj9",
  "W4hcMdBdGSkV",
  "WRebWQaRiq==",
  "eCkunftdVCkDWQS=",
  "mCorW7jWsW==",
  "F13cIrVcHby6rSkrW49R",
  "W6NcTcK=",
  "W55mvs7dQW==",
  "WR1Km8oFpG==",
  "C8kqtYRdTW==",
  "WP4xlmouxCoHWQRdJGGp",
  "DCkNWQVcRqK=",
  "hmkPWRe5wviHt3VdIa==",
  "WPrVcSok",
  "WQ0VW5GMW5ysvXNcNa==",
  "qCkLmmolsa==",
  "cmkvWR4EW5uAWRehnSkpWPW=",
  "pmonWRa=",
  "W6n4yXRdKq==",
  "W5RdUCo5WQC=",
  "iCoxWQNdKZS=",
  "WPavW6edW60=",
  "WQL4W7v4W7q=",
  "DSo+W7hdOY4=",
  "WPf6W6rCW53cS8ok",
  "ysCuW47dNq==",
  "wHq+W5ZdQhRcRCoKW4TjchKNW6Ww",
  "WPVcSc1pW6K=",
  "WOCzkq==",
  "WP7cS8ouu1pdI8o1xq==",
  "aCkppf3dV8kgWOu=",
  "vmk8CY7dSW==",
  "W73cQZBdGCk1",
  "sgRcIqVcJW==",
  "yYeghXG=",
  "WQFdJxysCq==",
  "w8kiWRtcGtpcGG==",
  "W7/dUsTIW4C=",
  "WQ4OW5uHW40urWFcNG==",
  "W4JcHSkch8kV",
  "W55CxJldKW==",
  "Cg0NW5bS",
  "W4RcQs7dGCkM",
  "u8omWPldMbLr",
  "WPZdK0OdymomW58rW4VcKmknrwPRWQ9a",
  "w8kQWOlcHuC=",
  "W5biqZxdLW==",
  "WRhdN8ojeLS=",
  "EwmDv1y9WQKv",
  "WOa3WP/dUMq=",
  "uCkstqhdVa==",
  "WO7cNWPHW4q=",
  "fIzpdCoIWRXMWPvH",
  "WOpdRSkIfXi=",
  "WOC4WRJdKKa=",
  "A0RcVd7cNa==",
  "WPecWPuxcG==",
  "emkShNZdSW==",
  "WOunlCosr8ofWRFdIW4t",
  "DmkfW4SbWOu=",
  "WOOdWPufkG==",
  "FCocWOJdKW==",
  "WR8QW48yW4e=",
  "qNdcPhdcJmk6",
  "F8kukmoLEG==",
  "WOvTmmokd8o4WPxcUa==",
  "WQBdKNRdSK4=",
  "ySkuFda=",
  "WPFcRc5aW4W=",
  "WOKupmowr8orWR/dJbiE",
  "g2ldRLOc",
  "eSoPW7HtvG==",
  "fSoaW4VcL1W=",
  "rmoXW4ldLWJdT2tdK8klowvQWRea",
  "WQZdUCkaasxcJmkgWOmka8kepW==",
  "u8oWW47dNbZdPMhdQSku",
  "WQewWQVdULi=",
  "W7xdRbDpW4i=",
  "zYNcJvmg",
  "WOJdGvqnuG==",
  "W6axWRBdN8o0fCovFLPzqgNdMwFdPfaoDG==",
  "CCkHW5GZWRi=",
  "zJmRW7NdGq==",
  "zvJcGhtcJa==",
  "hG7dGmkktq==",
  "kqBdICkQwG==",
  "W7H1oCkMWQq=",
  "W7tdQ8o7WQtcGG==",
  "W4fFuqZdOG==",
  "yCopW63dKGm=",
  "CSk6vb/dNW==",
  "WQO4W5u2W4SpwaZcIW==",
  "w8oXD8o/ya==",
  "WPCzWR8tfq==",
  "wu3cIIdcOa==",
  "W7lcNmkzjSkR",
  "kSk+WReGtG==",
  "W4CxWQRdGG==",
  "W7JdHbbUW40oW6xcRqdcUmkL",
  "WQqCWPCYkG==",
  "smkiW7WfWOms",
  "umkEeCoNuG==",
  "vmo2WQNdJdq=",
  "WRCIWPtdMvS=",
  "W77cVZ7dT8k3W6n8",
  "kuldPgaK",
  "W4hdVSk/nKi=",
  "WRjdW7jvW6u=",
  "WPRdRNNdM0W=",
  "gSoCW6NcPenEumoUWOi=",
  "gSocW6NcOffsBCoUWPtcUHDly8kAWPVdMa==",
  "aM/dU3C6sw3dO8oM",
  "mH1mdmod",
  "WPNdMemhy8oDW54iW6BcJCkxxMfgWQvCWQJdJmkoWRGSW67cNq==",
  "W6NdSSocWPhcIq==",
  "tSkmW6agWOmuW6ej",
  "F3FcTG7cRW==",
  "WRKZcCoFxW==",
  "sSk2EHldTW==",
  "FqS8ad0UD8ob",
  "iuxdMeeX",
  "y8o8zmkuoG==",
  "cmoxW7NcHeLsu8oUWOJcUdbaFSkx",
  "nCojWQ7dUWS=",
  "W6VcPmk6cSk7",
  "WRJdSCkWjrS=",
  "bSkrW6NcMNxcLSkzW6Xc",
  "smkLgCoPxSoWz33cRa==",
  "WP7dS8kNWO7cKG==",
  "k8onWRhdTW==",
  "vCopWPNdLH1lE1/cGG==",
  "WP7cGbb9W5pdQfW=",
  "o8osW6n7tCoXWQlcP8k8mq==",
  "WRSmW4VcH8ox",
  "WQGuW4qQW60=",
  "vg7cQ3BcNa==",
  "W4tdI8ouWRxcOG==",
  "FLVcRJZcKW==",
  "w8ogWOxdIa==",
  "W7vJlmkQWOq=",
  "WRddGemuDW==",
  "W6W5WPpdQ8o7",
  "ESk5W5m=",
  "WRpcGJjZW7C=",
  "WQavWQOepmkk",
  "D8kMuq/dMa==",
  "WQVdT2tdOKq=",
  "WOxdTSo8eea=",
  "W77cMmkqjW==",
  "WRW8WPtdL1C=",
  "W5GiWQFdJCoLnmoPBezQu37dO3RdJvq=",
  "WQJdT8knbd3cGmkSWPSMa8kw",
  "WRJdRSkNWQ/cLq==",
  "o0JdGfir",
  "iCo9W4NcHhPYCmoD",
  "bdvdeG==",
  "WQmeWRCvnSkqkI9H",
  "D8k2W5BdV8oudSkmWRNdNmkfW5rmurG=",
  "WPNdSmoWiq==",
  "WQ4rWRddUfm=",
  "WPlcJavLW53dRKa=",
  "WOjUcSoDga==",
  "etfchCo/WQfPWOb2",
  "W57dKW9QW49bW4xcOrdcUG==",
  "W6xdPXXpW6a=",
  "pCoqWQZdRJ3cR8kCk8oyWRLwgW==",
  "WR/dVCo7hNy=",
  "nCkfWOOltW==",
  "DSoXs8opuvVdICoeyCoijG==",
  "hfxdH14d",
  "r8kNWP/cILq=",
  "WOhdS27dQh0=",
  "s0CMW59XWRZcIqHd",
  "oSkjaK3dKa==",
  "CSoSW7tdRGi=",
  "n8oGW5xcH1m=",
  "dmkioeddPa==",
  "gmoAWOldTd0=",
  "x0/cLZRcHa==",
  "W7WFWPhdTSoq",
  "rmkoW50NWQW=",
  "W43dVSoKWOhcRa==",
  "xLGQW5nUWP/cGqfhsG==",
  "WRpdO8kKWQxcRa==",
  "AxaxFx8=",
  "WQNdQ8oumui=",
  "sSkjWQdcOK4=",
  "iqldLq==",
  "dSkaawZdPW==",
  "WOlcHHzQW5tdIve1WPese8kieWWyvq3cNd0=",
  "W6VcOYRdH8kZW7n8",
  "WOirW77cPSoE",
  "B8kLW4RdHmomfmkLWRVdLG==",
  "WQBdPmkPWRZcRG==",
  "xSobWRhdLIi=",
  "WP/dJ8kZWRxcPG==",
  "W7zftI/dGSk2ASkeltlcHSkUfCkS",
  "WRKhW57cT8ok",
  "dCoBW6pcPq==",
  "WRxdN8kqgau=",
  "W5b4eG==",
  "WOrfj8osoa==",
  "EqS+hZuIFa==",
  "WRWKWPhdMfC=",
  "yCkmWOtcH1C=",
  "W53dRrbXW4y=",
  "smk1fq==",
  "cCoxWOVdIHm=",
  "W7tcU8kIoSkt",
  "W6ynWRpdPmou",
  "W49ftJ/dJ8kbCCksmqm=",
  "FvVcV1FcHW==",
  "rmokASkbcCopW5z1W7W=",
  "WO7dLfWPESofW6ukW7C=",
  "sCkbW6SNWPC=",
  "umkAcSoRvmkZ",
  "qNWwq1uSWQGmWOBcJmkesKfXW7K=",
  "WRKXWPpdLuZcPa==",
  "lCo4W7ZcIMS=",
  "jWJdKmkYy8ouuhK=",
  "f8knjLddUmkuWQG=",
  "WQBdGK7dH0K=",
  "W7xcMCkDkSkBW5OstSkS",
  "WPtdSmkSWRhcHCog",
  "jt94gmo7",
  "uwzVWQZcLa==",
  "WQldT2FdTxRcJCkgjX4=",
  "rSkchmoLtCkZF8kgW4ddLu7cQSkoW4SVFq==",
  "WOuGWOeadq==",
  "japdHSkKBmosug8Z",
  "FCokW7RdJJC=",
  "a8orW5NcLvm=",
  "vN8auveNWRu=",
  "W5/dLmo7WRJcNq==",
  "yfNcLaZcIHW=",
  "WPiMW57cQG==",
  "wCowA8kc",
  "DmkaW4mKWPq=",
  "WPeLW4BcQmorWRDy",
  "qtxcLNmz",
  "WQxcImosD1i=",
  "WOPcW41CW70=",
  "C8oIsCkpcW==",
  "WOtcJavSW47dQeaM",
  "W6dcUIZdGCkMW6z7Egu=",
  "bcBdKCk5tG==",
  "WP3cNJTWW6y=",
  "yYVcSheV",
  "WQxdPSk4WRJcJmoyWRP/WO8=",
  "mCkfphVdHW==",
  "WQuAaConrG==",
  "W5nBW4JcGmknpW==",
  "BCoDW6RdSYG=",
  "DmkFW6m7WPq=",
  "W6tcQcZdJSk5",
  "WRWdWQWek8kSnJzJWPlcJG==",
  "WRtdRwmrvW==",
  "B8kIW5BdMa==",
  "WQWUf8oCwq==",
  "WQFdVMCczq==",
  "WPCzW74yW74=",
  "DuKAyfu=",
  "sxhcSa==",
  "rCkTW73dPmoe",
  "C8oiWQtdMG4=",
  "ncfOmmoG",
  "W4/dSCkSfq==",
  "v8k5aSoYrmoNDN7cVqmRWOK=",
  "vSk8g8oLra==",
  "FWJcPvaQncbNW68=",
  "BWeJmIe1DSoFWPLHWOJdS8kP",
  "W7/cLSkymG==",
  "WR/dG2mWrq==",
  "AXdcOfWGfsTRW6XtCW==",
  "yKRcLrZcIGuMzSkv",
  "FxXS",
  "W55pW4NcJSk4jrlcNgq/sW==",
  "WOhdVmo9j1C=",
  "oSohW5RcLKG=",
  "omooWQBdOGZcHmkCoSoZWRm=",
  "jgldMKiN",
  "W781WO0=",
  "dmkbgfxdIW==",
  "kajlnSou",
  "hmkVWReGueWHswy=",
  "WOBcIWa=",
  "CmoQw8opw1ZdIG==",
  "g8kLl3ZdKa==",
  "WPOFWO7dIwC=",
  "WQzOW7nzW5lcUCoWW7Dmo2pcTHpcP0TJsq==",
  "lmk1pNFdIa==",
  "W5T4aSk9WQmygKO=",
  "EWWT",
  "tSovD8oVyG==",
  "W4/dVmk2o08=",
  "WPJcSmoWtgu=",
  "WPRdHmkqaZS=",
  "WOBdTMRdPehcJCkjmG==",
  "W5VcKIRdHmkI",
  "WQ7cGZr8W70=",
  "W67dQSoIWRBcLCkoWP/cPHO=",
  "tsaHpJ0=",
  "xCo2s8odra==",
  "WOqzlCoEq8o3W77dJbuFkW==",
  "A2qYW55b",
  "WQCxpCosr8o8WRFdLqG=",
  "u2aqrhKUWQmwWRC=",
  "WRvCW411W7a=",
  "rCoSW4FdNGRdPG==",
  "yCoVvmobCW==",
  "DSkzkCo+CG==",
  "ESkIpSoiCG==",
  "yWa7W67dUa==",
  "W77cVZ7dT8k0W7rQzuGmkG==",
  "W4pcRdFdUSkG",
  "BmkEzr/dQa==",
  "WPxdN8ktddi=",
  "WRy/W487W4K=",
  "WOKxnSoCxmo3",
  "v3/cTwZcJCkwymoS",
  "W47dLSo6WQFcRG==",
  "WPVdMfWdD8okW5K=",
  "ws3cKv0M",
  "WO7dQgRdJ33cISkl",
  "WRS6WO4ffa==",
  "yCoSx8kddG==",
  "W4JcJrtdG8kT",
  "W4KTWPBdM8oD",
  "ySkKWQRcIIq=",
  "W4KuWQ3dO8oi",
  "x8kfW6ChWOGsW5W=",
  "yCkQeSo0Ba==",
  "xCofymkdgSohW591W6S=",
  "yCoTx8k9ca==",
  "Dw0UW7ni",
  "DCoVrCoUDG==",
  "BGNcOKaHocb2",
  "FIKkhXe=",
  "v3zSWOxdSCkoa3WsWRDcW6dcHSoV",
  "WR3cGCoQz2O=",
  "sComBSonqG==",
  "WPJcGG5XW4K=",
  "WO9IW6ffW53cUCoo",
  "W4PixY7dGq==",
  "W6FcQZNdUSkKW6LRCMuapa==",
  "W45EW4tcLCkg",
  "W4JcVCknoSkD",
];
r = d;
o = 175;
(function (e) {
  for (; --e; ) r.push(r.shift());
})(++o);

var f = function e(t, n) {
  // r即d序列中其中一条密码（d是旋转后的）
  var r = d[(t -= 0)];
  void 0 === e.YcraBi &&
    ((e.qZQcpm = function (e, t) {
      for (
        var n = [],
          r = 0,
          o = void 0,
          i = "",
          a = "",
          s = 0,
          u = (e = (function (e) {
            for (
              var t, n, r = String(e).replace(/=+$/, ""), o = "", i = 0, a = 0;
              (n = r.charAt(a++));
              ~n && ((t = i % 4 ? 64 * t + n : n), i++ % 4)
                ? (o += String.fromCharCode(255 & (t >> ((-2 * i) & 6))))
                : 0
            )
              n = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=".indexOf(
                n
              );
            return o;
          })(e)).length;
        s < u;
        s++
      )
        a += "%" + ("00" + e.charCodeAt(s).toString(16)).slice(-2);
      e = decodeURIComponent(a);
      var c = void 0;
      for (c = 0; c < 256; c++) n[c] = c;
      for (c = 0; c < 256; c++)
        (r = (r + n[c] + t.charCodeAt(c % t.length)) % 256),
          (o = n[c]),
          (n[c] = n[r]),
          (n[r] = o);
      (c = 0), (r = 0);
      for (var d = 0; d < e.length; d++)
        (r = (r + n[(c = (c + 1) % 256)]) % 256),
          (o = n[c]),
          (n[c] = n[r]),
          (n[r] = o),
          (i += String.fromCharCode(e.charCodeAt(d) ^ n[(n[c] + n[r]) % 256]));
      return i;
    }),
    (e.VJIJrx = {}),
    (e.YcraBi = !0));
  var o = e.VJIJrx[t];
  return (
    void 0 === o
      ? (void 0 === e.vqlFfC && (e.vqlFfC = !0),
        (r = e.qZQcpm(r, n)),
        (e.VJIJrx[t] = r))
      : (r = o),
    r
  );
};

module.exports = f;
